### ISSUE TITLE
Support for setting published ports in Pods

### ISSUE THREAD

**Issue by rlad78** [containers/podman-tui#127]
**Is your feature request related to a problem? Please describe.**
The "create" menu in Pods does not allow for setting published ports.

**Describe the solution you'd like**
A "Ports Settings" tab similar to what is available in the Containers menu.

**Additional context**
Quoting the Podman [podman-pod-create](https://docs.podman.io/en/latest/markdown/podman-pod-create.1.html#publish-p-ip-hostport-containerport-protocol) documentation directly:

> You must not publish ports of containers in the pod individually, but only by the pod itself.
> This cannot be modified once the pod is created.

Otherwise, I must say, this is a brilliant application and I greatly appreciate the work you've put into it!

**Comment by navidys** [comment]
Hi @rlad78 

Thanks for this and nice comment. 
It will be available in the next release.

**Comment by navidys** [comment]
Hi @rlad78 
#214 is adding this feature.

Regards
