### ISSUE TITLE
Build error archive.go:11:2: cannot find package "." in: /usr/src/podman-tui/vendor/io/fs

### ISSUE THREAD

**Issue by eMPee584** [containers/podman-tui#136]
Even though I ran `apt install make libgpgme-dev libbtrfs-dev libdevmapper-dev libassuan-dev pkg-config` before, building from `master` with `make binary` fails on debian 11.4:

```
running go build
go build -mod=vendor  -o ./bin/podman-tui
vendor/github.com/containers/storage/pkg/archive/archive.go:11:2: cannot find package "." in:
        /usr/src/podman-tui/vendor/io/fs
make: *** [Makefile:38: podman-tui] Error 1
```
🤔

**Comment by navidys** [comment]
Hi @eMPee584 
Thanks for reaching.
I think you are using default debian 11.4 go version (v1.15) and minimum required go version is 1.17. 

Regards

**Comment by eMPee584** [comment]
Ah thanks.. ok got it to work, only to find out debian's podman 3 is too old for this tool..
Well it will likely work at some point, so looking forward to that 😄
