### ISSUE TITLE
Please cut a new release for podman 4.3

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-tui#154]
New release of Podman, so we need a new release of podman-tui

**Comment by navidys** [comment]
Hi @rhatdan 

I have cut the release 0.6.0 for podman 4.2, waiting for 4.3 release and two more features for tui to include and then will cut the  release 0.7.0

**Comment by rhatdan** [comment]
SGTM

**Comment by navidys** [comment]
Hi @rhatdan 
branch "release-v0.7" available.

regards

**Comment by rhatdan** [comment]
Excellent.
