### ISSUE TITLE
Participating in Hacktoberfest?

### ISSUE THREAD

**Issue by jlosito** [containers/podman-tui#166]
**Is your feature request related to a problem? Please describe.**
I was wondering if this project was participating in hacktoberfest. I didn't see anything related to the topic, so I figured I'd ask.

https://hacktoberfest.com/participation/

**Describe the solution you'd like**
If participating in hacktoberfest, would it be possible to add the hacktoberfest topic to this project? If not, that's fine too.

**Comment by navidys** [comment]
Hi @jlosito 
No it was not participating.
