### ISSUE TITLE
Update docs to reflect API version >=3.1 + build info debian bullseye

### ISSUE THREAD

**Issue by ygaeon** [containers/podman-tui#19]
I'm running debian bullseye and spent some time getting podman-tui to build. When finally starting it up getting the error that the podman API version 3.0.0 is too old.

Perhaps also add the following build dependencies for debian bullseye users?
- libgpgme-dev
- libbtrfs-dev
- libdevmapper-dev

(I'd open a pr and make these changes myself, if I knew how) :-)

**Comment by navidys** [comment]
Hi @ygaeon 
Created PR #20.
