### ISSUE TITLE
Remove Select button to improve usability of the command menu

### ISSUE THREAD

**Issue by SmartFinn** [containers/podman-tui#202]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/819186/204095855-3d866db4-bf47-4439-983d-078e6d5b03c6.png)

This case a bit confused. While using I'm not 100% sure which button is selected. Select with magenta highlight, or Cancel with white highlight. The select button seems useless, the selected item of this menu is already select.

**Describe the solution you'd like**

Removing Select button fixes the issue. The Tab button behavior should be kept:

![mockup](https://user-images.githubusercontent.com/819186/204097379-6e635a63-6abc-45eb-b689-7701983f4dbc.gif)

**Additional context**

This mehanism uses [ncspot](https://github.com/hrkfdn/ncspot) in their context menus.

**Comment by navidys** [comment]
Hi @SmartFinn 
Thanks for this, would you like to PR the fix ?

**Comment by SmartFinn** [comment]
@navidys oh, no. I known how to fix it in GIMP, not in Go

**Comment by navidys** [comment]
@SmartFinn 
PR #212 implemeting the removal of "select button"

![command_dialog](https://user-images.githubusercontent.com/5696685/208221097-0da57609-f5a6-40bc-a585-2064bae44ed1.gif)
