### ISSUE TITLE
unable to connect to Podman socket

### ISSUE THREAD

**Issue by overtube** [containers/podman-tui#320]
`unable to connect to Podman socket: Get "http://d/v4.4.2/l/run/user/1000/podman/podman.soc or directory`

**Comment by Daredevil3869** [comment]
I am also having the same issue where even the socket is enabled I get this message ``unable to connect to Podman socket: Get "http://d/v4.4.2/l/run/user/1000/podman/podman.soc or directory`` 

systemctl status of podman.socket
```
[user@pc ~]$ systemctl status podman.socket
● podman.socket - Podman API Socket
     Loaded: loaded (/usr/lib/systemd/system/podman.socket; disabled; preset: disabled)
     Active: active (listening) since Sat 2023-08-05 18:28:19 PDT; 5min ago
   Triggers: ● podman.service
       Docs: man:podman-system-service(1)
     Listen: /run/podman/podman.sock (Stream)
     CGroup: /system.slice/podman.socket

```

OS: Fedora Silverblue (ublue)

**Comment by navidys** [comment]
Hi @Daredevil3869

Thanks for reporting this, I will look into it.
Can u please let me know if you are using the main branch or any specific version ?

**Comment by Daredevil3869** [comment]
The version of podman-tui I am using is the one provided by Fedora Silverblue  ``0.9.1-1.fc38``

**Comment by Daredevil3869** [comment]
I think I found the problem it was that I was not running ```podman-tui``` as sudo which fixed my problem

**Comment by navidys** [comment]
Hi @Daredevil3869 

Thanks, will close it.

**Comment by overtube** [comment]
all worked, thank!
