### ISSUE TITLE
Publish podman-tui to homebrew

### ISSUE THREAD

**Issue by FreddyFunk** [containers/podman-tui#434]
**Is your feature request related to a problem? Please describe.**
Currenlty the popular macOS package manager Homebrew is not supported, while other package manager for various Linux distros are supported. Building from source is doable, but keeping podman-tui up to date this way is a bit more annoying. Beeing able to use a package manager would be more convenient. 

**Describe the solution you'd like**
Publish podman-tui to Hombrew as well.

**Additional context**
Pleeeease :D

**Comment by navidys** [comment]
Hi @FreddyFunk 
Thanks for reaching out , sure will be available soon .

**Comment by navidys** [comment]
published to homebrew #436

**Comment by FreddyFunk** [comment]
Thank you :)
