### ISSUE TITLE
Replace purne by prune

### ISSUE THREAD

**Issue by eulores** [containers/podman-tui#514]
**Describe the bug**
There are eight files with text similar to _"system **purne** in progress"_ where **prune** is misspelled.
Suggest changing **purne** into **prune**.

See this [code search](https://github.com/search?q=repo%3Acontainers%2Fpodman-tui+purne&type=code)

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by eulores** [comment]
See pull request https://github.com/containers/podman-tui/pull/515
