### ISSUE TITLE
Add remote connection

### ISSUE THREAD

**Issue by matheusfenolio** [containers/podman-tui#58]
I have a server using Podman running in a cloud. 

1 - Is it possible to connect using podman-tui? 
2 - If yes, can you add an example about how-to?

**Comment by navidys** [comment]
Hi @matheusfenolio 
Thanks for reaching, podman-tui v0.3 (only for podman v4) supports remote system connections via SSH.

- Press "**F2**" and switch to system page
- Press "**m**" to open command dialog and select "**add connection**" 
- Fill out requires information and then add the connection
![add_connection](https://user-images.githubusercontent.com/5696685/163657075-ad15c0e4-7e0c-4914-9adc-728e372ce562.png)

If the SSH key has a passphrase, then you need to set and export "**CONTAINER_PASSPHRASE=\<password\>**" variable before running the application.

-  After adding the connection you can select "**connect**" from command dialog to connect to the remote node.

**Comment by dinotheextinct** [comment]
Can you pease elaborate how the passphrase is used? Chatgot is mit even able to und erstand its application without inspecting the image.
