### ISSUE TITLE
Pre-Built Binaries for Easy Installation

### ISSUE THREAD

**Issue by lesichkovm** [containers/podman-tui#84]
Is it possible to pre-build the binaries with each new release, so that it can be easily installed just by downloading via curl or wget like below?

```
wget PODMAN_TUI_RELEASE_URL
```

Otherwise one has to download the repository, install go, then build the app, which is a bit much

**Comment by navidys** [comment]
Hi @lesichkovm 

- For Fedora you can install the packaged version, however the latest release (0.3.1 for podman v4) is only available from FC36. 
I am planning to build packaged version under Fedora CORP so it will be easy to install and and test unreleased upstream code on FC35,FC36,... (its also possible to use "podman-tui.spec.rpkg" to build RPM package and install)
 
- For windows binary, I think we can add the pre-build binary from next release  this feature not available on previous releases).

**Comment by lesichkovm** [comment]
I was thinking more like having something like this (see example below), where each release gets the binaries built and attached to the release.

Example: https://github.com/mailhog/MailHog/releases/tag/v1.0.1

Then depending on OS the user can download what he needs

**Comment by eMPee584** [comment]
Yeah I tried converting the Fedora RPM to deb but it needs a higher glibc than the 2.31 that comes with bullseye #sad :panda_face:

**Comment by navidys** [comment]
Hi @lesichkovm , @eMPee584 
static build binaries for Linux, windows and darwin are available from release v0.7.0.
